JSON file for movies
mkor92/Uppgift2-Biograf pull request #31
Opened 2022-12-29 10:54 UTC by mkor92

A total of 18 movies, mixed Drama, Comedy and Action

2022-12-29 11:13 UTC, matodorovic reviewed
Maybe it is not good that u merged footer into ur branch since Olliver closed PR without merging?

2022-12-29 11:13 UTC, matodorovic commented on index.html
> +        <img src="static/images/Logo.png" alt="logo" />
Good 👍

2022-12-29 11:19 UTC, mkor92 commented
> 

I solved conflicts that where there

2022-12-29 11:24 UTC, matodorovic approved these changes
Okej than. I understand. Great job with JSON file!

2022-12-29 11:52 UTC, matodorovic approved these changes

2022-12-29 14:08 UTC, jakobpalmborg requested changes
Looks good! One thing we could think about is if we should create one propertie with date and time. I think that it would fit our design of the webpage better. 

Here is a link about date and time format in json

https://docs.jsonata.org/date-time

2022-12-29 15:34 UTC, matodorovic approved these changes
It seems that it is even better now with date.

2022-12-29 15:34 UTC, matodorovic commented on src/filmer.json
> +      "dates": ["9/1/2023", "11/1/2023", "13/1/2023"],
Maybe it would be good to use date format Date("2021-01-01T12:00:00Z") so than we don't need times, just 
[ "2023-01-15T12:00:00Z", "2023-01-15T15:00:00Z", "2023-01-15T20:30:00Z", "2023-01-19T12:00:00Z", "2023-01-19T15:00:00Z", "2023-01-19T20:30:00Z", "2023-01-25T20:30:00Z", "2023-01-25T116:00:00Z"] ?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

2022-12-29 15:34 UTC, matodorovic commented on src/filmer.json
> +      "dateTime": ["2023-1-9T13:45", "2023-1-11T16:30", "2023-1-13T17:45"],
Looks good now. 👌

2022-12-29 15:38 UTC, matodorovic approved these changes

2022-12-30 08:24 UTC, jakobpalmborg approved these changes
The dateTime in json file looks great now! I think this will be amazing when we use it later.

2022-12-30 08:24 UTC, merged